// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'cs'

export type Locales =
	| 'cs'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	candidate: {
		auth: {
			login: {
				/**
				 * P​ř​i​h​l​á​š​e​n​í
				 */
				title: string
				/**
				 * E​v​i​d​e​n​č​n​í​ ​č​í​s​l​o​ ​j​e​ ​j​e​d​i​n​e​č​n​é​ ​č​í​s​l​o​ ​p​ř​i​d​ě​l​e​n​é​ ​u​c​h​a​z​e​č​i​,​ ​k​t​e​r​é​ ​s​l​o​u​ž​í​ ​k​ ​j​e​h​o​ ​i​d​e​n​t​i​f​i​k​a​c​i​
			​a​p​ř​i​h​l​á​š​e​n​í​ ​s​e​ ​d​o​ ​s​y​s​t​é​m​u​.
				 */
				description: string
			}
		}
	}
}

export type TranslationFunctions = {
	candidate: {
		auth: {
			login: {
				/**
				 * Přihlášení
				 */
				title: () => LocalizedString
				/**
				 * Evidenční číslo je jedinečné číslo přidělené uchazeči, které slouží k jeho identifikaci
			apřihlášení se do systému.
				 */
				description: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
