//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::admin::Entity as Admin;
pub use super::admin_session::Entity as AdminSession;
pub use super::candidate::Entity as Candidate;
pub use super::parent::Entity as Parent;
pub use super::session::Entity as Session;
